server:
  port: 5000
  tomcat:
    threads:
      max: 200
spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 10s
        pool:
          max-connections: 1000
          max-idle-time: 5000
          acquire-timeout: 5000
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: oss
          uri: lb://dev-sphere-oss-dev
          predicates:
            - Path=/oss/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,  REQUEST_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
        - id: auth
          uri: lb://dev-sphere-auth-dev
          predicates:
            - Path=/auth/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,  REQUEST_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
        - id: subject
          uri: lb://dev-sphere-subject-dev
          predicates:
            - Path=/subject/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,  REQUEST_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
        - id: circle
          uri: lb://dev-sphere-circle-dev
          predicates:
            - Path=/share/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,  REQUEST_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
      enabled: true

  # redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 14.103.134.185
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: C020611.
    # 连接超时时间
    timeout: 2s
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000ms
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接池中的最小空闲连接
        min-idle: 20
sa-token:
  token-prefix: cccs7
  # token 名称（同时也是 cookie 名称）
  token-name: cccs7
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true