server:
  port: 80
  tomcat:
    max-connections: 1024
    connection-timeout: 10000

spring:
  # redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 14.103.134.185
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: C020611.
    # 连接超时时间
    timeout: 5s
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
      cluster:
        refresh:
          adaptive: true
          period: 600000