server:
  port: 8089
  tomcat:
    max-connections: 1024
    connection-timeout: 10000

spring:
  datasource:
    username: cccs7
    password: C020611.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.92.68.100/dev-sphere?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
#      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: cccs7
        login-password: C020611.
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
  # redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 14.103.134.185
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: C020611.
    # 连接超时时间
    timeout: 5s
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10s
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接池中的最小空闲连接
        min-idle: 5
es:
  cluster:
    esConfigs[0]:
      name: 6570b6c6d1dd
      nodes: 14.103.134.185:9200
logging:
  config: classpath:log4j2-spring.xml
