server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://dev-sphere-oss-dev
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1